# Generated by Django 4.1.7 on 2023-07-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='data_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='data_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='data_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='born',
            field=models.DateField(),
        ),
    ]
