# Generated by Django 4.1.7 on 2023-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_education_data_end_alter_experience_data_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='tasks',
            field=models.TextField(help_text='Введите свой опыт', max_length=5000, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='about',
            field=models.TextField(help_text='Кратко о себе', max_length=2000, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='hobbies',
            field=models.TextField(help_text='Введите свое хобби', max_length=2000, verbose_name='Хобби'),
        ),
    ]
