# Generated by Django 4.1.7 on 2023-07-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_experience_tasks_alter_skill_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesireRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire_role', models.CharField(max_length=50)),
            ],
        ),
    ]
