# Generated by Django 4.1.7 on 2023-07-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_experience_briefly'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univer', models.CharField(max_length=250)),
                ('specialty', models.CharField(max_length=250)),
                ('data_end', models.DateField()),
            ],
        ),
    ]
